package tablas;
// Generated 14-feb-2022 13:11:52 by Hibernate Tools 4.0.1.Final

import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;

import conexionBBDD.Persistencia;
import conexionBBDD.PersistenciaMysql;
import interfaz.VentanaInicial;
import utilidades.Utilidades;

/**
 * Alimento generated by hbm2java
 */
public class Alimento  extends ElementoPadre implements java.io.Serializable {
	private Integer id;
	private String descripcion;
	private double coste;
	private Set consumes = new HashSet(0);

	//___MÉTODOS PARA LA PERSISTENCIA JDBC
			public String[] getNombreCampos(){
				return new String[] {"id", "descripcion", "coste"};
			}	

			public String[] getCampos() throws ParseException {
				return new String[] {String.valueOf(id), descripcion, String.valueOf(coste)};
			}
			
			public void configurar(String[] valores, Persistencia per) throws SQLException, Exception {
				id=Integer.valueOf(valores[0]);
				descripcion=valores[1];
				coste=Double.valueOf(valores[2]);
			}
			
			public Set<Consume> getConsumes(Persistencia per) {
				if(per instanceof PersistenciaMysql) {
					return getGenericSet(per, "Consume", "Alimento", this.id);
				} else {
					return getConsumes();
				}
			}
		//___MÉTODOS PARA LA PERSISTENCIA JDBC
	
	public Alimento() {
	}

	public Alimento(String descripcion, double coste) {
		this.descripcion = descripcion;
		this.coste = coste;
	}

	public Alimento(String descripcion, double coste, Set consumes) {
		this.descripcion = descripcion;
		this.coste = coste;
		this.consumes = consumes;
	}

	public Integer getId() {
		return this.id;
	}
	
	public Integer obtenerId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public double getCoste() {
		return this.coste;
	}

	public void setCoste(double coste) {
		this.coste = coste;
	}

	public Set<Consume> getConsumes() {
		return this.consumes;
	}

	public void setConsumes(Set consumes) {
		this.consumes = consumes;
	}

}
