package tablas;
// Generated 14-feb-2022 13:11:52 by Hibernate Tools 4.0.1.Final

import java.util.Date;

/**
 * AnimaltratamientoId generated by hbm2java
 */
public class AnimaltratamientoId implements java.io.Serializable {

	private int idAnimal;
	private int idEmpleado;
	private int idTratamiento;
	private Date fechaHora;

	@Override
	public String toString() {
		return "AnimaltratamientoId [idAnimal=" + idAnimal + ", idEmpleado=" + idEmpleado + ", idTratamiento="
				+ idTratamiento + ", fechaHora=" + fechaHora + "]";
	}

	public AnimaltratamientoId() {
	}

	public AnimaltratamientoId(int idAnimal, int idEmpleado, int idTratamiento, Date fechaHora) {
		this.idAnimal = idAnimal;
		this.idEmpleado = idEmpleado;
		this.idTratamiento = idTratamiento;
		this.fechaHora = fechaHora;
	}

	public int getIdAnimal() {
		return this.idAnimal;
	}

	public void setIdAnimal(int idAnimal) {
		this.idAnimal = idAnimal;
	}

	public int getIdEmpleado() {
		return this.idEmpleado;
	}

	public void setIdEmpleado(int idEmpleado) {
		this.idEmpleado = idEmpleado;
	}

	public int getIdTratamiento() {
		return this.idTratamiento;
	}

	public void setIdTratamiento(int idTratamiento) {
		this.idTratamiento = idTratamiento;
	}

	public Date getFechaHora() {
		return this.fechaHora;
	}

	public void setFechaHora(Date fechaHora) {
		this.fechaHora = fechaHora;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AnimaltratamientoId))
			return false;
		AnimaltratamientoId castOther = (AnimaltratamientoId) other;

		return (this.getIdAnimal() == castOther.getIdAnimal()) && (this.getIdEmpleado() == castOther.getIdEmpleado())
				&& (this.getIdTratamiento() == castOther.getIdTratamiento())
				&& ((this.getFechaHora() == castOther.getFechaHora()) || (this.getFechaHora() != null
						&& castOther.getFechaHora() != null && this.getFechaHora().equals(castOther.getFechaHora())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdAnimal();
		result = 37 * result + this.getIdEmpleado();
		result = 37 * result + this.getIdTratamiento();
		result = 37 * result + (getFechaHora() == null ? 0 : this.getFechaHora().hashCode());
		return result;
	}

}
