package tablas;
// Generated 14-feb-2022 13:11:52 by Hibernate Tools 4.0.1.Final

import java.sql.SQLException;

import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import conexionBBDD.Persistencia;
import conexionBBDD.PersistenciaMysql;
import interfaz.VentanaInicial;
import utilidades.Utilidades;

/**
 * Animal generated by hbm2java
 */
public class Animal extends ElementoPadre implements java.io.Serializable {

	private Integer id;
	private Especie especie;
	private Zona zona;
	private String nombre;
	private Date fechaNac;
	private Set animaltratamientos = new HashSet(0);
	private Set consumes = new HashSet(0);
	
	public String toString() {
		return "Animal [id=" + id + ", especie=" + especie + ", zona=" + zona + ", nombre=" + nombre + ", fechaNac="
				+ fechaNac + "]";
	}
	
	//___MÉTODOS PARA LA PERSISTENCIA JDBC
		public String[] getNombreCampos(){
			return new String[] {"id", "nombre", "idEspecie", "idZona", "fechaNac"};
		}
	
		public String[] getCampos() throws ParseException {
			String fechaMysql = Utilidades.getFechaStringMysql(fechaNac);
			return new String[] {String.valueOf(id), nombre, String.valueOf(especie.getId()), String.valueOf(zona.getId()), fechaMysql};
		}
		
		public void configurar(String[] valores, Persistencia per) throws SQLException, Exception {
			id=Integer.valueOf(valores[0]);
			nombre=valores[1];
			String idEspecie=valores[2];
			String idZona=valores[3];
	
			fechaNac=Utilidades.getFechaDateMysql(valores[4]);
			
			especie = (Especie) per.getObjetoMulti("Especie", new String[] {"id", idEspecie});
			zona = (Zona) per.getObjetoMulti("Zona", new String[] {"id", idZona});
		}
		public Set<Animaltratamiento> getAnimaltratamientos(Persistencia per) {
			if(per instanceof PersistenciaMysql) {
				return getGenericSet(per, "Animaltratamiento", "Animal", this.id);
			} else {
				return getAnimaltratamientos();
			}
		}
		
		public Set<Consume> getConsumes(Persistencia per) {
			if(per instanceof PersistenciaMysql) {
				return getGenericSet(per, "Consume", "Animal", this.id);
			} else {
				return getConsumes();
			}
		}
	//___MÉTODOS PARA LA PERSISTENCIA JDBC
	
	public Animal() {
	}

	public Animal(Zona zona, Especie especie, String nombre, Date fechaNac) {
		this.zona = zona;
		this.especie = especie;
		this.nombre = nombre;
		this.fechaNac = fechaNac;
	}
	
	public Animal(Integer id, Zona zona, Especie especie, String nombre, Date fechaNac) {
		this(zona, especie, nombre, fechaNac);
		this.id = id;
	}

	public Integer getId() {
		return this.id;
	}

	public Integer obtenerId() {
		return this.id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}

	public Especie getEspecie() {
		return this.especie;
	}

	public void setEspecie(Especie especie) {
		this.especie = especie;
	}

	public Zona getZona() {
		return this.zona;
	}

	public void setZona(Zona zona) {
		this.zona = zona;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFechaNac() {
		return this.fechaNac;
	}

	public void setFechaNac(Date fechaNac) {
		this.fechaNac = fechaNac;
	}

	public Set<Animaltratamiento> getAnimaltratamientos() {
		return this.animaltratamientos;
	}
	
	public void setAnimaltratamientos(Set animaltratamientos) {
		this.animaltratamientos = animaltratamientos;
	}

	public Set<Consume> getConsumes() {
		return this.consumes;
	}

	public void setConsumes(Set consumes) {
		this.consumes = consumes;
	}

}
