package tablas;
// Generated 14-feb-2022 13:11:52 by Hibernate Tools 4.0.1.Final

import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import conexionBBDD.Persistencia;
import conexionBBDD.PersistenciaMysql;
import utilidades.Utilidades;

/**
 * Empleado generated by hbm2java
 */
public class Empleado extends ElementoPadre implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private Date fechaNac;
	private String direccion;
	private Set nominas = new HashSet(0);
	private Set animaltratamientos = new HashSet(0);
	private Set tratamientos = new HashSet(0);
	private Set zonas = new HashSet(0);



	//___MÉTODOS PARA LA PERSISTENCIA JDBC
		public String[] getNombreCampos(){
			return new String[] {"id", "nombre", "fechaNac", "direccion"};
		}
	
		public String[] getCampos() throws ParseException {
			String fechaMysql = Utilidades.getFechaStringMysql(fechaNac);
			return new String[] {String.valueOf(id), nombre, fechaMysql, direccion};
		}
		
		public void configurar(String[] valores, Persistencia per) throws SQLException, Exception {
			id=Integer.valueOf(valores[0]);
			nombre=valores[1];
			fechaNac=Utilidades.getFechaDateMysql(valores[2]);
			direccion=valores[3];
		}
		public Set<Animaltratamiento> getAnimaltratamientos(Persistencia per) {
			if(per instanceof PersistenciaMysql) {
				return getGenericSet(per, "Animaltratamiento", "Empleado", this.id);
			} else {
				return getAnimaltratamientos();
			}
		}
		
		public Set<Nomina> getNominas(Persistencia per) {
			if(per instanceof PersistenciaMysql) {
				return getGenericSet(per, "Nomina", "Empleado", this.id);
			} else {
				return getNominas();
			}
		}
		public Set<Tratamiento> getTratamientos(Persistencia per) {
			if(per instanceof PersistenciaMysql) {
				return getGenericSetTablaInter(per, "Tratamiento", "escapaz", "Empleado", this.id);
			} else {
				return getTratamientos();
			}
		}
		public Set<Zona> getZonas(Persistencia per) {
			if(per instanceof PersistenciaMysql) {
				return getGenericSetTablaInter(per, "Zona", "trabaja", "Empleado", this.id);
			} else {
				return getZonas();
			}
		}

		
	//___EQUALS
		
		@Override
		public int hashCode() {
			final int prime = 31;
			int result = 1;
			result = prime * result + ((id == null) ? 0 : id.hashCode());
			return result;
		}

		@Override
		public boolean equals(Object obj) {
			if (this == obj)
				return true;
			if (obj == null)
				return false;
			if (getClass() != obj.getClass())
				return false;
			Empleado other = (Empleado) obj;
			if (id == null) {
				if (other.id != null)
					return false;
			} else if (!id.equals(other.id))
				return false;
			return true;
		}
		
	//___MÉTODOS AUTOGENERADOS

	public Empleado() {
	}

	public Empleado(String nombre, Date fechaNac, String direccion) {
		this.nombre = nombre;
		this.fechaNac = fechaNac;
		this.direccion = direccion;
	}

	public Empleado(String nombre, Date fechaNac, String direccion, Set nominas, Set animaltratamientos,
			Set tratamientos, Set zonas) {
		this.nombre = nombre;
		this.fechaNac = fechaNac;
		this.direccion = direccion;
		this.nominas = nominas;
		this.animaltratamientos = animaltratamientos;
		this.tratamientos = tratamientos;
		this.zonas = zonas;
	}

	public String toString() {
		return "Empleado [id=" + id + ", nombre=" + nombre + ", fechaNac=" + fechaNac + ", direccion=" + direccion
				+ "]";
	}

	public Integer getId() {
		return this.id;
	}
	
	public Integer obtenerId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFechaNac() {
		return this.fechaNac;
	}

	public void setFechaNac(Date fechaNac) {
		this.fechaNac = fechaNac;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public Set getNominas() {
		return this.nominas;
	}

	public void setNominas(Set nominas) {
		this.nominas = nominas;
	}

	public Set getAnimaltratamientos() {
		return this.animaltratamientos;
	}

	public void setAnimaltratamientos(Set animaltratamientos) {
		this.animaltratamientos = animaltratamientos;
	}

	public Set getTratamientos() {
		return this.tratamientos;
	}

	public void setTratamientos(Set tratamientos) {
		this.tratamientos = tratamientos;
	}

	public Set getZonas() {
		return this.zonas;
	}

	public void setZonas(Set zonas) {
		this.zonas = zonas;
	}

}
