package tablas;
// Generated 14-feb-2022 13:11:52 by Hibernate Tools 4.0.1.Final

import java.sql.SQLException;
import java.text.ParseException;
import java.util.HashSet;
import java.util.Set;

import conexionBBDD.Persistencia;
import conexionBBDD.PersistenciaMysql;

/**
 * Especie generated by hbm2java
 */
public class Especie extends ElementoPadre implements java.io.Serializable {

	private Integer id;
	private String descripcion;
	private Set animals = new HashSet(0);

	
	public String toString() {
		return "Especie [id=" + id + ", descripcion=" + descripcion + "]";
	}
	
	//___MÉTODOS PARA LA PERSISTENCIA JDBC
		public String[] getNombreCampos(){
			return new String[] {"id", "descripcion"};
		}	

		public String[] getCampos() throws ParseException {
			return new String[] {String.valueOf(id), descripcion};
		}

		public void configurar(String[] valores, Persistencia per) throws SQLException, Exception {
			id=Integer.valueOf(valores[0]);
			descripcion=valores[1];
		}
		public Set<Animal> getAnimals(Persistencia per) {
			if(per instanceof PersistenciaMysql) {
				return getGenericSet(per, "Animal", "Especie", this.id);
			} else {
				return getAnimals();
			}
		}
	//___MÉTODOS PARA LA PERSISTENCIA JDBC

	public Especie() {
	}

	public Especie(String descripcion) {
		this.descripcion = descripcion;
	}

	public Especie(String descripcion, Set animals) {
		this.descripcion = descripcion;
		this.animals = animals;
	}

	public Integer getId() {
		return this.id;
	}
	
	public Integer obtenerId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getAnimals() {
		return this.animals;
	}

	public void setAnimals(Set animals) {
		this.animals = animals;
	}

}
