package tablas;
// Generated 14-feb-2022 13:11:52 by Hibernate Tools 4.0.1.Final

import java.sql.SQLException;
import java.text.ParseException;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import conexionBBDD.Persistencia;
import conexionBBDD.PersistenciaMysql;
import utilidades.Utilidades;

/**
 * Evento generated by hbm2java
 */
public class Evento extends ElementoPadre implements java.io.Serializable {

	private Integer id;
	private String descripcion;
	private double precio;
	private Date horaInicio;
	private Date horaFin;
	private Set entradas = new HashSet(0);

	//___MÉTODOS PARA LA PERSISTENCIA JDBC
			public String[] getNombreCampos(){
				return new String[] {"id", "descripcion", "precio", "horaInicio", "horaFin"};
			}
		
			public String[] getCampos() throws ParseException {
				String fechaMysqlIni = Utilidades.getHoraStringMysql(horaInicio);
				String fechaMysqlFin = Utilidades.getHoraStringMysql(horaFin);
				return new String[] {String.valueOf(id), descripcion, String.valueOf(precio), fechaMysqlIni, fechaMysqlFin};
			}
			
			public void configurar(String[] valores, Persistencia per) throws SQLException, Exception {
				id=Integer.valueOf(valores[0]);
				descripcion=valores[1];
				precio=Double.valueOf(valores[2]);
				horaInicio=Utilidades.getHoraDateMysql(valores[3]);
				horaFin=Utilidades.getHoraDateMysql(valores[4]);
			}
			public Set<Entrada> getEntradas(Persistencia per) {
				if(per instanceof PersistenciaMysql) {
					return getGenericSet(per, "Entrada", "Evento", this.id);
				} else {
					return getEntradas();
				}
			}
	//___MÉTODOS PARA LA PERSISTENCIA JDBC
	
	public Evento() {
	}

	public Evento(String descripcion, double precio) {
		this.descripcion = descripcion;
		this.precio = precio;
	}

	public Evento(String descripcion, double precio, Date horaInicio, Date horaFin, Set entradas) {
		this.descripcion = descripcion;
		this.precio = precio;
		this.horaInicio = horaInicio;
		this.horaFin = horaFin;
		this.entradas = entradas;
	}

	public Integer getId() {
		return this.id;
	}
	
	public Integer obtenerId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public double getPrecio() {
		return this.precio;
	}

	public void setPrecio(double precio) {
		this.precio = precio;
	}

	public Date getHoraInicio() {
		return this.horaInicio;
	}

	public void setHoraInicio(Date horaInicio) {
		this.horaInicio = horaInicio;
	}

	public Date getHoraFin() {
		return this.horaFin;
	}

	public void setHoraFin(Date horaFin) {
		this.horaFin = horaFin;
	}

	public Set<Entrada> getEntradas() {
		return this.entradas;
	}

	public void setEntradas(Set entradas) {
		this.entradas = entradas;
	}

}
