package tablas;
// Generated 14-feb-2022 13:11:52 by Hibernate Tools 4.0.1.Final

import java.sql.SQLException;
import java.text.ParseException;
import java.util.Date;

import conexionBBDD.Persistencia;
import utilidades.Utilidades;

/**
 * Nomina generated by hbm2java
 */
public class Nomina extends ElementoPadre implements java.io.Serializable, Comparable<Nomina> {

	private Integer id;
	private Date fechaEmision;
	private double importeBruto;
	private double irpf;
	private double segSocial;
	private Empleado empleado;

	//___MÉTODOS PARA LA PERSISTENCIA JDBC
		public String[] getNombreCampos(){
			return new String[] {"id", "fechaEmision", "importeBruto", "irpf", "segSocial", "idEmpleado"};
		}
	
		public String[] getCampos() throws ParseException {
			String fechaMysql = Utilidades.getFechaStringMysql(fechaEmision);
			return new String[] {String.valueOf(id), fechaMysql, String.valueOf(importeBruto), String.valueOf(irpf), String.valueOf(segSocial),String.valueOf(empleado.getId())};
		}
		
		public void configurar(String[] valores, Persistencia per) throws SQLException, Exception {
			id=Integer.valueOf(valores[0]);
			fechaEmision=Utilidades.getFechaDateMysql(valores[1]);
			importeBruto=Double.valueOf(valores[2]);
			irpf=Double.valueOf(valores[3]);
			segSocial=Double.valueOf(valores[4]);
			
			String idEmpleado=valores[5];		
			empleado = (Empleado) per.getObjetoMulti("Empleado", new String[] {"id", idEmpleado});
		}
	//___MÉTODOS PARA LA PERSISTENCIA JDBC
	
		
	public Nomina() {
	}

	public String toString() {
		return "Nomina [id=" + id + ", fechaEmision=" + fechaEmision + ", importeBruto=" + importeBruto + ", irpf="
				+ irpf + ", segSocial=" + segSocial + ", empleado=" + empleado + "]";
	}

	public Nomina(int id, Empleado empleado, Date fechaEmision, double importeBruto, double irpf, double segSocial) {
		this(empleado, fechaEmision, importeBruto, irpf, segSocial);
		this.id = id;
	}
	
	public Nomina(Empleado empleado, Date fechaEmision, double importeBruto, double irpf, double segSocial) {
		this.empleado = empleado;
		this.fechaEmision = fechaEmision;
		this.importeBruto = importeBruto;
		this.irpf = irpf;
		this.segSocial = segSocial;
	}

	public Integer getId() {
		return this.id;
	}

	public Integer obtenerId() {
		return this.id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}

	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	public Date getFechaEmision() {
		return this.fechaEmision;
	}

	public void setFechaEmision(Date fechaEmision) {
		this.fechaEmision = fechaEmision;
	}

	public double getImporteBruto() {
		return this.importeBruto;
	}

	public void setImporteBruto(double importeBruto) {
		this.importeBruto = importeBruto;
	}

	public double getIrpf() {
		return this.irpf;
	}

	public void setIrpf(double irpf) {
		this.irpf = irpf;
	}

	public double getSegSocial() {
		return this.segSocial;
	}

	public void setSegSocial(double segSocial) {
		this.segSocial = segSocial;
	}
	
	public int compareTo(Nomina o) {
		return this.fechaEmision.compareTo(o.fechaEmision)*-1;
	}

}
