package tablas;
// Generated 14-feb-2022 13:11:52 by Hibernate Tools 4.0.1.Final

import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;

import conexionBBDD.Persistencia;
import conexionBBDD.PersistenciaMysql;
import interfaz.VentanaInicial;
import utilidades.Utilidades;

/**
 * Tratamiento generated by hbm2java
 */
public class Tratamiento extends ElementoPadre implements java.io.Serializable {

	private Integer id;
	private String descripcion;
	private double coste;
	private Set animaltratamientos = new HashSet(0);
	private Set empleados = new HashSet(0);

	//___MÉTODOS PARA LA PERSISTENCIA JDBC
		public String[] getNombreCampos(){
			return new String[] {"id", "descripcion", "coste"};
		}	
	
		public String[] getCampos() throws ParseException {
			return new String[] {String.valueOf(id), descripcion, String.valueOf(coste)};
		}
		
		public void configurar(String[] valores, Persistencia per) throws SQLException, Exception {
			id=Integer.valueOf(valores[0]);
			descripcion=valores[1];
			coste=Double.valueOf(valores[2]);
		}
		public Set<Animaltratamiento> getAnimaltratamientos(Persistencia per) {
			if(per instanceof PersistenciaMysql) {
				return getGenericSet(per, "Animaltratamiento", "Tratamiento", this.id);
			} else {
				return getAnimaltratamientos();
			}
		}
		public Set<Empleado> getEmpleados(Persistencia per) {
			if(per instanceof PersistenciaMysql) {
				return getGenericSetTablaInter(per, "Empleado", "escapaz", "Tratamiento", this.id);
			} else {
				return getEmpleados();
			}
		}
	//___MÉTODOS PARA LA PERSISTENCIA JDBC
	
	public String toString() {
		return "Tratamiento [id=" + id + ", descripcion=" + descripcion + ", coste=" + coste + "]";
	}

	public Tratamiento() {
	}

	public Tratamiento(String descripcion, double coste) {
		this.descripcion = descripcion;
		this.coste = coste;
	}

	public Tratamiento(String descripcion, double coste, Set animaltratamientos, Set empleados) {
		this.descripcion = descripcion;
		this.coste = coste;
		this.animaltratamientos = animaltratamientos;
		this.empleados = empleados;
	}

	public Integer getId() {
		return this.id;
	}

	public Integer obtenerId() {
		return this.id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public double getCoste() {
		return this.coste;
	}

	public void setCoste(double coste) {
		this.coste = coste;
	}

	public Set getAnimaltratamientos() {
		return this.animaltratamientos;
	}

	public void setAnimaltratamientos(Set animaltratamientos) {
		this.animaltratamientos = animaltratamientos;
	}

	public Set getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Set empleados) {
		this.empleados = empleados;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Tratamiento other = (Tratamiento) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}
	
	

}
