package tablas;
// Generated 14-feb-2022 13:11:52 by Hibernate Tools 4.0.1.Final

import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;

import conexionBBDD.Persistencia;
import conexionBBDD.PersistenciaMysql;
import utilidades.Utilidades;

/**
 * Zona generated by hbm2java
 */
public class Zona extends ElementoPadre implements java.io.Serializable {

	private Integer id;
	private String descripcion;
	private Set animals = new HashSet(0);
	private Set empleados = new HashSet(0);

	
	//___MÉTODOS PARA LA PERSISTENCIA JDBC
		public String[] getNombreCampos(){
			return new String[] {"id", "descripcion"};
		}	

		public String[] getCampos() throws ParseException {
			return new String[] {String.valueOf(id), descripcion};
		}
		
		public void configurar(String[] valores, Persistencia per) throws SQLException, Exception {
			id=Integer.valueOf(valores[0]);
			descripcion=valores[1];
		}
		public Set<Animal> getAnimals(Persistencia per) {
			if(per instanceof PersistenciaMysql) {
				return getGenericSet(per, "Animal", "Zona", this.id);
			} else {
				return getAnimals();
			}
		}
		public Set<Empleado> getEmpleados(Persistencia per) {
			if(per instanceof PersistenciaMysql) {
				return getGenericSetTablaInter(per, "Empleado", "trabaja", "Zona", this.id);
			} else {
				return getEmpleados();
			}
		}
	//___MÉTODOS PARA LA PERSISTENCIA JDBC
	
	public Zona() {
	}

	public Zona(String descripcion) {
		this.descripcion = descripcion;
	}

	public Zona(String descripcion, Set animals, Set empleados) {
		this.descripcion = descripcion;
		this.animals = animals;
		this.empleados = empleados;
	}

	public Integer getId() {
		return this.id;
	}
	
	public Integer obtenerId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set<Animal> getAnimals() {
		return this.animals;
	}

	public void setAnimals(Set animals) {
		this.animals = animals;
	}

	public Set<Empleado> getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Set empleados) {
		this.empleados = empleados;
	}

}
